name: Run Tests on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Replace this with the version of Node.js your project requires

      - name: Install Yarn dependencies
        run: yarn install

      - name: Run tests
        run: yarn test:ci
