name: Run Auth Tests on Pull Request

on:
  pull_request:
    paths:
      - "auth/**"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && npm i && npm run test:ci
